/*
 * port.h
 *
 *  Created on: Mar 8, 2019
 *      Author: emon1
 */

#ifndef C12832_C12832_PORT_H_
#define C12832_C12832_PORT_H_

#include "stm32l4xx.h"
#include "stm32l4xx_hal.h"

#endif /* C12832_C12832_PORT_H_ */

#define DISPLAY_A0_Pin GPIO_PIN_0
#define DISPLAY_A0_GPIO_Port GPIOC
#define DISPLAY_BACKLIGHT_Pin GPIO_PIN_1
#define DISPLAY_BACKLIGHT_GPIO_Port GPIOC
#define DISPLAY_nSEL_Pin GPIO_PIN_2
#define DISPLAY_nSEL_GPIO_Port GPIOC
#define DISPLAY_nRESET_Pin GPIO_PIN_3
#define DISPLAY_nRESET_GPIO_Port GPIOC

#define DISPLAY_CHIP_SELECT_LOW      			HAL_GPIO_WritePin (DISPLAY_nSEL_GPIO_Port, DISPLAY_nSEL_Pin, GPIO_PIN_RESET)
#define DISPLAY_CHIP_SELECT_HIGH				HAL_GPIO_WritePin (DISPLAY_nSEL_GPIO_Port, DISPLAY_nSEL_Pin, GPIO_PIN_SET)

#define DISPLAY_A0_LOW      					HAL_GPIO_WritePin (DISPLAY_A0_GPIO_Port, DISPLAY_A0_Pin, GPIO_PIN_RESET)
#define DISPLAY_A0_HIGH							HAL_GPIO_WritePin (DISPLAY_A0_GPIO_Port, DISPLAY_A0_Pin, GPIO_PIN_SET)

#define DISPLAY_RESET_LOW      					HAL_GPIO_WritePin (DISPLAY_nRESET_GPIO_Port, DISPLAY_nRESET_Pin, GPIO_PIN_RESET)
#define DISPLAY_RESET_HIGH						HAL_GPIO_WritePin (DISPLAY_nRESET_GPIO_Port, DISPLAY_nRESET_Pin, GPIO_PIN_SET)

#define DISPLAY_BACKLIGHT_OFF  					HAL_GPIO_WritePin (DISPLAY_BACKLIGHT_GPIO_Port, DISPLAY_BACKLIGHT_Pin, GPIO_PIN_RESET)
#define DISPLAY_BACKLIGHT_ON					HAL_GPIO_WritePin (DISPLAY_BACKLIGHT_GPIO_Port, DISPLAY_BACKLIGHT_Pin, GPIO_PIN_SET)




void C12832_Port_Init(void);

int hal_spi_write_read (uint8_t *tx_data, uint8_t *rx_data, uint16_t lenght);

